#include "sam_cpuid.h"

PROCESSOR_LIST                              //Processeur                        Family  Model   Stepping    Type    L1      L2
ProcessorList[]  = {  { "AuthenticAMD",     "Am486/Am5x86",                     4,     -1,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K5 Model 0",                   5,      0,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K5 Model 1",                   5,      1,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K5 Model 2",                   5,      2,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K5 Model 3",                   5,      3,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K6 Model 6",                   5,      6,      -1,         -1,     32,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K6 Model 7",                   5,      7,      -1,         -1,     32,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K6-2 Model 8",                 5,      8,      -1,         -1,     32,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K6-III Model 9",               5,      9,      -1,         -1,     32,     -1, 0 },
                      { "AuthenticAMD",     "AMD-K6-2+ / III+",                 5,     13,      -1,         -1,     32,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon Model 1",               6,      1,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon Model 2",               6,      2,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Duron Model 3",                6,      3,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon Thunderbird",           6,      4,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonXP Palomino",            6,      6,       2,         -1,     64,    256, 0 },
                      { "AuthenticAMD",     "AMD Athlon Model 6",               6,      6,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Duron Model 7",                6,      7,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonXP Thoroughbred",        6,      8,       1,         -1,     64,    256, 0 },
                      { "AuthenticAMD",     "AMD AthlonXP Model 8",             6,      8,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonXP Barton",              6,     10,       0,         -1,     64,    512, 0 },
                      { "AuthenticAMD",     "AMD AthlonXP Model 10",            6,     10,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonX2",                    15,      3,       2,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon64 Model 4",            15,      4,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD Opteron Model 5",             15,      5,      -1,         -1,     -1,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon64",                    15,      7,       1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon64",                    15,      7,      10,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonX2",                    15,     11,       1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD AthlonX2",                    15,     11,       2,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon/Opteron ???",          15,     11,      -1,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon64",                    15,     15,       0,         -1,     64,     -1, 0 },
                      { "AuthenticAMD",     "AMD Athlon64",                    15,     15,       2,         -1,     64,     -1, 0 },

                      { "AuthenticAMD",     "AMD ???",                         -1,     -1,      -1,         -1,     -1,     -1, 0 },

                      { "GenuineIntel",     "Intel486",                         4,     -1,      -1,         -1,     -1,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium 60/66 (5Volts)",     5,      1,      -1,         -1,      8,     -1, 0 },

                      { "GenuineIntel",     "Intel Pentium 75-200",             5,      2,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium MMX",                5,      4,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel MobilePentium 75-200",       5,      7,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel MobilePentium MMX",          5,      8,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium",                    5,     -1,      -1,         -1,      8,     -1, 0 },

                      { "GenuineIntel",     "Intel Pentium Pro",                6,      1,      -1,         -1,      8,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium II Klamath",         6,      3,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium II Model 5",         6,      5,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel MobilePentium II / Celeron", 6,      6,      -1,         -1,     -1,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III Katmai",         6,      7,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-E",              6,      8,       1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-E",              6,      8,       2,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-EB",             6,      8,       3,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-EB",             6,      8,       6,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium M",                  6,      9,      -1,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Pentium III-Xeon (Model A)", 6,     10,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-S (FC-PGA2)",    6,     11,       1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium III-S (Model B)",    6,     11,      -1,         -1,     16,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium M (Model D)",        6,     13,      -1,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Pentium M",                  6,     14,      -1,         -1,     16,     -1, 1 },

                      { "GenuineIntel",     "Intel Core 2 Duo",                 6,     15,       2,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Core 2 Duo",                 6,     15,       4,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Core 2 Duo",                 6,     15,       6,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Core 2 Quad",                6,     15,       7,         -1,     16,     -1, 1 },
                      

                      { "GenuineIntel",     "Intel Pentium M",                  6,     15,      -1,         -1,     16,     -1, 1 },
                      { "GenuineIntel",     "Intel Pentium Pro/II/III",         6,     -1,      -1,         -1,     -1,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium IV (Model 0-0.18)", 15,      0,      -1,         -1,     12,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium IV (Model 1-0.18)", 15,      1,      -1,         -1,     12,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium IV (Model 2-0.13)", 15,      2,      -1,         -1,     12,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium IV (Model 3-90nm)", 15,      3,      -1,         -1,     12,     -1, 0 },
                      { "GenuineIntel",     "Intel Pentium IV",                15,     -1,      -1,         -1,     -1,     -1, 0 },
                      { "GenuineIntel",     "Intel ???",                       -1,     -1,      -1,         -1,     -1,     -1, 0 },

                      { "CyrixInstead",     "Cyrix ???",                       -1,     -1,      -1,         -1,     -1,     -1, 0 },
                      { "",                 "???",                             -1,     -1,      -1,         -1,     -1,     -1, 0 } };
